[package]
name = "rusty-term-cli"
version = "0.1.0"
edition = "2021"
author = "Residuum22"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]